


val colors = listof(
    NamedColor(
        "aliceblue",0xFf0f8ff),NamedColor(
        "antiquewhite",0xFfaebd7),NamedColor(
        "aqua",0xF00ffff),NamedColor(
        "aquamarine",0xF7fffd4),NamedColor(
        "azure",0xFf0ffff),NamedColor(
        "beige",0xFf5f5dc),NamedColor(
        "bisque",0xFffe4c4),NamedColor(
        "black",0xF000000),NamedColor(
        "blanchedalmond",0xFffebcd),NamedColor(
        "blue",0xF0000ff),NamedColor(
        "blueviolet",0xF8a2be2),NamedColor(
        "brown",0xFa52a2a),NamedColor(
        "burlywood",0xFdeb887),NamedColor(
        "cadetblue",0xF5f9ea0),NamedColor(
        "chartreuse",0xF7fff00),NamedColor(
        "chocolate",0xFd2691e),NamedColor(
        "coral",0xFff7f50),NamedColor(
        "cornflowerblue",0xF6495ed),NamedColor(
        "cornsilk",0xFfff8dc),NamedColor(
        "crimson",0xFdc143c),NamedColor(
        "cyan",0xF00ffff),NamedColor(
        "darkblue",0xF00008b),NamedColor(
        "darkcyan",0xF008b8b),NamedColor(
        "darkgoldenrod",0xFb8860b),NamedColor(
        "darkgray",0xFa9a9a9),NamedColor(
        "darkgreen",0xF006400),NamedColor(
        "darkgrey",0xFa9a9a9),NamedColor(
        "darkkhaki",0xFbdb76b),NamedColor(
        "darkmagenta",0xF8b008b),NamedColor(
        "darkolivegreen",0xF556b2f),NamedColor(
        "darkorange",0xFff8c00),NamedColor(
        "darkorchid",0xF9932cc),NamedColor(
        "darkred",0xF8b0000),NamedColor(
        "darksalmon",0xFe9967a),NamedColor(
        "darkseagreen",0xF8fbc8f),NamedColor(
        "darkslateblue",0xF483d8b),NamedColor(
        "darkslategray",0xF2f4f4f),NamedColor(
        "darkslategrey",0xF2f4f4f),NamedColor(
        "darkturquoise",0xF00ced1),NamedColor(
        "darkviolet",0xF9400d3),NamedColor(
        "deeppink",0xFff1493),NamedColor(
        "deepskyblue",0xF00bfff),NamedColor(
        "dimgray",0xF696969),NamedColor(
        "dimgrey",0xF696969),NamedColor(
        "dodgerblue",0xF1e90ff),NamedColor(
        "firebrick",0xFb22222),NamedColor(
        "floralwhite",0xFfffaf0),NamedColor(
        "forestgreen",0xF228b22),NamedColor(
        "fuchsia",0xFff00ff),NamedColor(
        "gainsboro",0xFdcdcdc),NamedColor(
        "ghostwhite",0xFf8f8ff),NamedColor(
        "goldenrod",0xFdaa520),NamedColor(
        "gold",0xFffd700),NamedColor(
        "gray",0xF808080),NamedColor(
        "green",0xF008000),NamedColor(
        "greenyellow",0xFadff2f),NamedColor(
        "grey",0xF808080),NamedColor(
        "honeydew",0xFf0fff0),NamedColor(
        "hotpink",0xFff69b4),NamedColor(
        "indianred",0xFcd5c5c),NamedColor(
        "indigo",0xF4b0082),NamedColor(
        "ivory",0xFfffff0),NamedColor(
        "khaki",0xFf0e68c),NamedColor(
        "lavenderblush",0xFfff0f5),NamedColor(
        "lavender",0xFe6e6fa),NamedColor(
        "lawngreen",0xF7cfc00),NamedColor(
        "lemonchiffon",0xFfffacd),NamedColor(
        "lightblue",0xFadd8e6),NamedColor(
        "lightcoral",0xFf08080),NamedColor(
        "lightcyan",0xFe0ffff),NamedColor(
        "lightgoldenrodyellow",0xFfafad2),NamedColor(
        "lightgray",0xFd3d3d3),NamedColor(
        "lightgreen",0xF90ee90),NamedColor(
        "lightgrey",0xFd3d3d3),NamedColor(
        "lightpink",0xFffb6c1),NamedColor(
        "lightsalmon",0xFffa07a),NamedColor(
        "lightseagreen",0xF20b2aa),NamedColor(
        "lightskyblue",0xF87cefa),NamedColor(
        "lightslategray",0xF778899),NamedColor(
        "lightslategrey",0xF778899),NamedColor(
        "lightsteelblue",0xFb0c4de),NamedColor(
        "lightyellow",0xFffffe0),NamedColor(
        "lime",0xF00ff00),NamedColor(
        "limegreen",0xF32cd32),NamedColor(
        "linen",0xFfaf0e6),NamedColor(
        "magenta",0xFff00ff),NamedColor(
        "maroon",0xF800000),NamedColor(
        "mediumaquamarine",0xF66cdaa),NamedColor(
        "mediumblue",0xF0000cd),NamedColor(
        "mediumorchid",0xFba55d3),NamedColor(
        "mediumpurple",0xF9370db),NamedColor(
        "mediumseagreen",0xF3cb371),NamedColor(
        "mediumslateblue",0xF7b68ee),NamedColor(
        "mediumspringgreen",0xF00fa9a),NamedColor(
        "mediumturquoise",0xF48d1cc),NamedColor(
        "mediumvioletred",0xFc71585),NamedColor(
        "midnightblue",0xF191970),NamedColor(
        "mintcream",0xFf5fffa),NamedColor(
        "mistyrose",0xFffe4e1),NamedColor(
        "moccasin",0xFffe4b5),NamedColor(
        "navajowhite",0xFffdead),NamedColor(
        "navy",0xF000080),NamedColor(
        "oldlace",0xFfdf5e6),NamedColor(
        "olive",0xF808000),NamedColor(
        "olivedrab",0xF6b8e23),NamedColor(
        "orange",0xFffa500),NamedColor(
        "orangered",0xFff4500),NamedColor(
        "orchid",0xFda70d6),NamedColor(
        "palegoldenrod",0xFeee8aa),NamedColor(
        "palegreen",0xF98fb98),NamedColor(
        "paleturquoise",0xFafeeee),NamedColor(
        "palevioletred",0xFdb7093),NamedColor(
        "papayawhip",0xFffefd5),NamedColor(
        "peachpuff",0xFffdab9),NamedColor(
        "peru",0xFcd853f),NamedColor(
        "pink",0xFffc0cb),NamedColor(
        "plum",0xFdda0dd),NamedColor(
        "powderblue",0xFb0e0e6),NamedColor(
        "purple",0xF800080),NamedColor(
        "rebeccapurple",0xF663399),NamedColor(
        "red",0xFff0000),NamedColor(
        "rosybrown",0xFbc8f8f),NamedColor(
        "royalblue",0xF4169e1),NamedColor(
        "saddlebrown",0xF8b4513),NamedColor(
        "salmon",0xFfa8072),NamedColor(
        "sandybrown",0xFf4a460),NamedColor(
        "seagreen",0xF2e8b57),NamedColor(
        "seashell",0xFfff5ee),NamedColor(
        "sienna",0xFa0522d),NamedColor(
        "silver",0xFc0c0c0),NamedColor(
        "skyblue",0xF87ceeb),NamedColor(
        "slateblue",0xF6a5acd),NamedColor(
        "slategray",0xF708090),NamedColor(
        "slategrey",0xF708090),NamedColor(
        "snow",0xFfffafa),NamedColor(
        "springgreen",0xF00ff7f),NamedColor(
        "steelblue",0xF4682b4),NamedColor(
        "tan",0xFd2b48c),NamedColor(
        "teal",0xF008080),NamedColor(
        "thistle",0xFd8bfd8),NamedColor(
        "tomato",0xFff6347),NamedColor(
        "turquoise",0xF40e0d0),NamedColor(
        "violet",0xFee82ee),NamedColor(
        "wheat",0xFf5deb3),NamedColor(
        "white",0xFffffff),NamedColor(
        "whitesmoke",0xFf5f5f5),NamedColor(
        "yellow",0xFffff00),
        NamedColor("yellowgreen",0xF9acd32)
)

